on:
  push:
    tags:
      - "-v[0-9]+.*"
name: Build and release Taskizer
jobs:
  prepareRelease:
    name: Prepare release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    outputs:
      upload_url: ${{ steps.prepareRelease.outputs.upload_url }}
    steps:
      - name: Create release
        id: createRelease
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
  buildAndReleaseAssetsOnWin:
    name: Build and release assets on Win
    needs: prepareRelease
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v1
      # Cache Node modules
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Setup Node
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Build
      - name: npm install and npm run
        run: |
          npm install
          npm run buildWin32
          npm run buildWin64
  buildAndReleaseAssetsOnLinux:
    name: Build and release assets on Linux
    needs: prepareRelease
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v1
      # Cache Node modules
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Setup Node
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Build
      - name: npm install and npm run
        run: |
          npm install
          npm run buildLinux32
          npm run buildLinux64
  buildAndReleaseAssetsOnMac:
    name: Build and release assets Mac
    needs: prepareRelease
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v1
      # Cache Node modules
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Setup Node
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Build on Mac
      - name: npm install and npm run
        run: |
          npm install
          npm run buildMac32
          npm run buildMac64